update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,22 +5,32 @@ jobs:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
-      - run: echo "we are building" 
-      - run: sleep 5
+      - run: mkdir -p my_workspace
+      - run: echo "Hello World" > my_workspace/echo-output
+      - persist_to_workspace:
+        root: my_workspace
+        paths:
+          - echo-output
   testa:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
-      - checkout
-      - run: echo "we are testing a" 
-      - run: sleep 5
+      - attach_workspace:
+        at: my_workspace
+      - run: cat my_workspace/echo-output
   testb:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
-      - checkout
-      - run: echo "we are testing b" 
-      - run: sleep 5
+      - attach_workspace:
+        at: my_workspace
+      - run: |
+          # this will fail intentionally, we'll use SSH to debug and fix
+          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
+            echo "It worked!";
+          else
+            echo "Nope!"; exit 1
+          fi 
   deploy:
     docker:
       - image: circleci/ruby:2.4.1
